### ISSUE TITLE
Fix network connection

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-developer-sandbox#18]
Network is not working on the VM per default.

### RCA
AWS has it's own *netplan* configuration which defines a configuration only for `eth0`, the default AWS nw interface. In a VM (qemu for example) the name might be different,  for example `enp1s0`.
In order to make the network run, we need to remove the AWS netplan configuration and add another one.
I suggest to use the default Ubuntu netplan configuration, as it seems to work with virtual network devices:

```
# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
```

### Steps to fix
1. Create a new Ansible step to remove the old netplan configuration under /etc/netplan
2. Copy a new configuration under /etc/netplan
3. run `sudo netplan generate` and `sud netplan apply`
